### ISSUE TITLE
[Bug] Installation failing on MacOS M1

### ISSUE THREAD

**Issue by matteobettini** [instadeepai/marl-eval#32]
When trying to install on Mac with 
`pip install "git+https://github.com/instadeepai/marl-eval.git"`

I get a building failed error when building `arch==5.0.1 ` 

## System info
- Mac OS Ventura 13.5.2 with Apple M1 Pro
- fresh arm conda env with python 3.8

**Comment by RuanJohn** [comment]
Hey @matteobettini, thank you for raising this.
I just made some dependency fixes this morning and at the moment it seems to working fine on M1 although I have macOS Ventura 13.2 (22D49). Could you please check if this is still an issue on your side?

**Comment by matteobettini** [comment]
It seems to work now, thanks for this!
